language: generic

services:
  - docker

before_install:
  - docker-compose pull rails

install:
  - docker-compose build rails

before_script:
  - docker-compose run rails bin/rails db:create
  - docker-compose run rails bin/rails db:schema:load

script:
  - docker-compose run rails yarn run lint
  - docker-compose run rails bin/rubocop
  - docker-compose run rails bin/rspec

before_cache:
  - sudo rm -fr coverage public/uploads/* tmp/cache tmp/uploads

after_success:
  - docker-compose down --volumes --remove-orphans

before_deploy:
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker-compose push rails

deploy:
  provider: script
  script: bash ./build_production.sh
  on:
    branch: it52
