language: generic

services:
  - docker

before_install:
- cp config/database.yml.template config/database.yml
- cp config/secrets.yml.template config/secrets.yml
- cp config/application.yml.template config/application.yml
- docker-compose pull
- docker-compose build rails

script:
- docker-compose run rails yarn run lint
- docker-compose run rails bin/rubocop
- docker-compose run rails bin/rails db:create
- docker-compose run rails bin/rails db:schema:load
- docker-compose run rails bin/rspec

before_deploy:
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker-compose push rails

deploy:
  provider: script
  script: build_production.sh
  on:
    branch: it52
