version: '3.2'
services:
  backend: &backend
    image: it52/rails:production
    build:
      context: .
      dockerfile: Dockerfile.production
      cache_from:
        - it52/rails:production
      args:
        - RAILS_MASTER_KEY=${RAILS_MASTER_KEY}
        - VCS_REF=${VCS_REF}
        - BUILD_DATE=${BUILD_DATE}
        - VERSION=${VERSION}

    tmpfs:
      - /tmp
    stdin_open: true
    tty: true
    volumes:
      - .:/it52:cached
      - node_modules:/it52/node_modules
      - bundle:/it52/vendor/bundle
    env_file:
      - '.env'
    environment:
      - NODE_ENV=production
      - RAILS_ENV=production
      - RAILS_MASTER_KEY=${RAILS_MASTER_KEY}

  rails:
    <<: *backend
    command: bundle exec rails server -p 3000 -b 0.0.0.0
    ports:
      - '3000:3000'
    depends_on:
      - postgres
      - redis

  sidekiq:
    <<: *backend
    command: bundle exec sidekiq -C config/sidekiq.yml
    depends_on:
      - postgres
      - redis

volumes:
  postgres:
  redis:
  bundle:
  node_modules:
